from setuptools import setup

setup(
    name='Json_Reader',
    version='',
    packages=['lab3_1.venv.Lib.site-packages.pip', 'lab3_1.venv.Lib.site-packages.pip._vendor',
              'lab3_1.venv.Lib.site-packages.pip._vendor.idna', 'lab3_1.venv.Lib.site-packages.pip._vendor.pep517',
              'lab3_1.venv.Lib.site-packages.pip._vendor.pytoml', 'lab3_1.venv.Lib.site-packages.pip._vendor.certifi',
              'lab3_1.venv.Lib.site-packages.pip._vendor.chardet',
              'lab3_1.venv.Lib.site-packages.pip._vendor.chardet.cli',
              'lab3_1.venv.Lib.site-packages.pip._vendor.distlib',
              'lab3_1.venv.Lib.site-packages.pip._vendor.distlib._backport',
              'lab3_1.venv.Lib.site-packages.pip._vendor.msgpack', 'lab3_1.venv.Lib.site-packages.pip._vendor.urllib3',
              'lab3_1.venv.Lib.site-packages.pip._vendor.urllib3.util',
              'lab3_1.venv.Lib.site-packages.pip._vendor.urllib3.contrib',
              'lab3_1.venv.Lib.site-packages.pip._vendor.urllib3.contrib._securetransport',
              'lab3_1.venv.Lib.site-packages.pip._vendor.urllib3.packages',
              'lab3_1.venv.Lib.site-packages.pip._vendor.urllib3.packages.backports',
              'lab3_1.venv.Lib.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              'lab3_1.venv.Lib.site-packages.pip._vendor.colorama',
              'lab3_1.venv.Lib.site-packages.pip._vendor.html5lib',
              'lab3_1.venv.Lib.site-packages.pip._vendor.html5lib._trie',
              'lab3_1.venv.Lib.site-packages.pip._vendor.html5lib.filters',
              'lab3_1.venv.Lib.site-packages.pip._vendor.html5lib.treewalkers',
              'lab3_1.venv.Lib.site-packages.pip._vendor.html5lib.treeadapters',
              'lab3_1.venv.Lib.site-packages.pip._vendor.html5lib.treebuilders',
              'lab3_1.venv.Lib.site-packages.pip._vendor.lockfile',
              'lab3_1.venv.Lib.site-packages.pip._vendor.progress',
              'lab3_1.venv.Lib.site-packages.pip._vendor.requests',
              'lab3_1.venv.Lib.site-packages.pip._vendor.packaging',
              'lab3_1.venv.Lib.site-packages.pip._vendor.cachecontrol',
              'lab3_1.venv.Lib.site-packages.pip._vendor.cachecontrol.caches',
              'lab3_1.venv.Lib.site-packages.pip._vendor.webencodings',
              'lab3_1.venv.Lib.site-packages.pip._vendor.pkg_resources', 'lab3_1.venv.Lib.site-packages.pip._internal',
              'lab3_1.venv.Lib.site-packages.pip._internal.cli', 'lab3_1.venv.Lib.site-packages.pip._internal.req',
              'lab3_1.venv.Lib.site-packages.pip._internal.vcs', 'lab3_1.venv.Lib.site-packages.pip._internal.utils',
              'lab3_1.venv.Lib.site-packages.pip._internal.models',
              'lab3_1.venv.Lib.site-packages.pip._internal.commands',
              'lab3_1.venv.Lib.site-packages.pip._internal.operations', 'lab3_1.venv.Lib.site-packages.idna',
              'lab3_1.venv.Lib.site-packages.click', 'lab3_1.venv.Lib.site-packages.flask',
              'lab3_1.venv.Lib.site-packages.flask.json', 'lab3_1.venv.Lib.site-packages.jinja2',
              'lab3_1.venv.Lib.site-packages.certifi', 'lab3_1.venv.Lib.site-packages.chardet',
              'lab3_1.venv.Lib.site-packages.chardet.cli', 'lab3_1.venv.Lib.site-packages.urllib3',
              'lab3_1.venv.Lib.site-packages.urllib3.util', 'lab3_1.venv.Lib.site-packages.urllib3.contrib',
              'lab3_1.venv.Lib.site-packages.urllib3.contrib._securetransport',
              'lab3_1.venv.Lib.site-packages.urllib3.packages',
              'lab3_1.venv.Lib.site-packages.urllib3.packages.backports',
              'lab3_1.venv.Lib.site-packages.urllib3.packages.ssl_match_hostname',
              'lab3_1.venv.Lib.site-packages.requests', 'lab3_1.venv.Lib.site-packages.werkzeug',
              'lab3_1.venv.Lib.site-packages.werkzeug.debug', 'lab3_1.venv.Lib.site-packages.werkzeug.contrib',
              'lab3_1.venv.Lib.site-packages.markupsafe', 'lab3_1.venv.Lib.site-packages.itsdangerous',
              'lab3_1.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip',
              'lab3_1.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor',
              'lab3_1.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.idna',
              'lab3_1.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.pytoml',
              'lab3_1.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.certifi',
              'lab3_1.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.chardet',
              'lab3_1.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.chardet.cli',
              'lab3_1.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.distlib',
              'lab3_1.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.distlib._backport',
              'lab3_1.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.msgpack',
              'lab3_1.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3',
              'lab3_1.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.util',
              'lab3_1.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.contrib',
              'lab3_1.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.contrib._securetransport',
              'lab3_1.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.packages',
              'lab3_1.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.packages.backports',
              'lab3_1.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.packages.ssl_match_hostname',
              'lab3_1.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.colorama',
              'lab3_1.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib',
              'lab3_1.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib._trie',
              'lab3_1.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.filters',
              'lab3_1.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.treewalkers',
              'lab3_1.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.treeadapters',
              'lab3_1.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.treebuilders',
              'lab3_1.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.lockfile',
              'lab3_1.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.progress',
              'lab3_1.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.requests',
              'lab3_1.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.packaging',
              'lab3_1.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.cachecontrol',
              'lab3_1.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.cachecontrol.caches',
              'lab3_1.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.webencodings',
              'lab3_1.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.pkg_resources',
              'lab3_1.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal',
              'lab3_1.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.req',
              'lab3_1.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.vcs',
              'lab3_1.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.utils',
              'lab3_1.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.models',
              'lab3_1.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.commands',
              'lab3_1.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.operations',
              'lab3_2.venv.Lib.site-packages.idna', 'lab3_2.venv.Lib.site-packages.past',
              'lab3_2.venv.Lib.site-packages.past.tests', 'lab3_2.venv.Lib.site-packages.past.types',
              'lab3_2.venv.Lib.site-packages.past.utils', 'lab3_2.venv.Lib.site-packages.past.builtins',
              'lab3_2.venv.Lib.site-packages.past.translation', 'lab3_2.venv.Lib.site-packages.click',
              'lab3_2.venv.Lib.site-packages.flask', 'lab3_2.venv.Lib.site-packages.flask.json',
              'lab3_2.venv.Lib.site-packages.numpy', 'lab3_2.venv.Lib.site-packages.numpy.ma',
              'lab3_2.venv.Lib.site-packages.numpy.ma.tests', 'lab3_2.venv.Lib.site-packages.numpy.doc',
              'lab3_2.venv.Lib.site-packages.numpy.fft', 'lab3_2.venv.Lib.site-packages.numpy.fft.tests',
              'lab3_2.venv.Lib.site-packages.numpy.lib', 'lab3_2.venv.Lib.site-packages.numpy.lib.tests',
              'lab3_2.venv.Lib.site-packages.numpy.core', 'lab3_2.venv.Lib.site-packages.numpy.core.tests',
              'lab3_2.venv.Lib.site-packages.numpy.f2py', 'lab3_2.venv.Lib.site-packages.numpy.f2py.tests',
              'lab3_2.venv.Lib.site-packages.numpy.tests', 'lab3_2.venv.Lib.site-packages.numpy.compat',
              'lab3_2.venv.Lib.site-packages.numpy.compat.tests', 'lab3_2.venv.Lib.site-packages.numpy.linalg',
              'lab3_2.venv.Lib.site-packages.numpy.linalg.tests', 'lab3_2.venv.Lib.site-packages.numpy.random',
              'lab3_2.venv.Lib.site-packages.numpy.random.tests', 'lab3_2.venv.Lib.site-packages.numpy.testing',
              'lab3_2.venv.Lib.site-packages.numpy.testing.tests',
              'lab3_2.venv.Lib.site-packages.numpy.testing._private', 'lab3_2.venv.Lib.site-packages.numpy.distutils',
              'lab3_2.venv.Lib.site-packages.numpy.distutils.tests',
              'lab3_2.venv.Lib.site-packages.numpy.distutils.command',
              'lab3_2.venv.Lib.site-packages.numpy.distutils.fcompiler',
              'lab3_2.venv.Lib.site-packages.numpy.matrixlib', 'lab3_2.venv.Lib.site-packages.numpy.matrixlib.tests',
              'lab3_2.venv.Lib.site-packages.numpy.polynomial', 'lab3_2.venv.Lib.site-packages.numpy.polynomial.tests',
              'lab3_2.venv.Lib.site-packages.branca', 'lab3_2.venv.Lib.site-packages.branca.plugins',
              'lab3_2.venv.Lib.site-packages.folium', 'lab3_2.venv.Lib.site-packages.folium.plugins',
              'lab3_2.venv.Lib.site-packages.future', 'lab3_2.venv.Lib.site-packages.future.moves',
              'lab3_2.venv.Lib.site-packages.future.moves.dbm', 'lab3_2.venv.Lib.site-packages.future.moves.html',
              'lab3_2.venv.Lib.site-packages.future.moves.http', 'lab3_2.venv.Lib.site-packages.future.moves.test',
              'lab3_2.venv.Lib.site-packages.future.moves.urllib', 'lab3_2.venv.Lib.site-packages.future.moves.xmlrpc',
              'lab3_2.venv.Lib.site-packages.future.moves.tkinter', 'lab3_2.venv.Lib.site-packages.future.tests',
              'lab3_2.venv.Lib.site-packages.future.types', 'lab3_2.venv.Lib.site-packages.future.utils',
              'lab3_2.venv.Lib.site-packages.future.builtins', 'lab3_2.venv.Lib.site-packages.future.backports',
              'lab3_2.venv.Lib.site-packages.future.backports.html',
              'lab3_2.venv.Lib.site-packages.future.backports.http',
              'lab3_2.venv.Lib.site-packages.future.backports.test',
              'lab3_2.venv.Lib.site-packages.future.backports.email',
              'lab3_2.venv.Lib.site-packages.future.backports.email.mime',
              'lab3_2.venv.Lib.site-packages.future.backports.urllib',
              'lab3_2.venv.Lib.site-packages.future.backports.xmlrpc',
              'lab3_2.venv.Lib.site-packages.future.standard_library', 'lab3_2.venv.Lib.site-packages.jinja2',
              'lab3_2.venv.Lib.site-packages.certifi', 'lab3_2.venv.Lib.site-packages.chardet',
              'lab3_2.venv.Lib.site-packages.chardet.cli', 'lab3_2.venv.Lib.site-packages.ratelim',
              'lab3_2.venv.Lib.site-packages.urllib3', 'lab3_2.venv.Lib.site-packages.urllib3.util',
              'lab3_2.venv.Lib.site-packages.urllib3.contrib',
              'lab3_2.venv.Lib.site-packages.urllib3.contrib._securetransport',
              'lab3_2.venv.Lib.site-packages.urllib3.packages',
              'lab3_2.venv.Lib.site-packages.urllib3.packages.backports',
              'lab3_2.venv.Lib.site-packages.urllib3.packages.ssl_match_hostname',
              'lab3_2.venv.Lib.site-packages.geocoder', 'lab3_2.venv.Lib.site-packages.requests',
              'lab3_2.venv.Lib.site-packages.werkzeug', 'lab3_2.venv.Lib.site-packages.werkzeug.debug',
              'lab3_2.venv.Lib.site-packages.werkzeug.contrib', 'lab3_2.venv.Lib.site-packages.markupsafe',
              'lab3_2.venv.Lib.site-packages.libfuturize', 'lab3_2.venv.Lib.site-packages.libfuturize.fixes',
              'lab3_2.venv.Lib.site-packages.itsdangerous', 'lab3_2.venv.Lib.site-packages.libpasteurize',
              'lab3_2.venv.Lib.site-packages.libpasteurize.fixes',
              'lab3_2.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip',
              'lab3_2.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor',
              'lab3_2.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.idna',
              'lab3_2.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.pytoml',
              'lab3_2.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.certifi',
              'lab3_2.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.chardet',
              'lab3_2.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.chardet.cli',
              'lab3_2.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.distlib',
              'lab3_2.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.distlib._backport',
              'lab3_2.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.msgpack',
              'lab3_2.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3',
              'lab3_2.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.util',
              'lab3_2.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.contrib',
              'lab3_2.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.contrib._securetransport',
              'lab3_2.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.packages',
              'lab3_2.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.packages.backports',
              'lab3_2.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.packages.ssl_match_hostname',
              'lab3_2.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.colorama',
              'lab3_2.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib',
              'lab3_2.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib._trie',
              'lab3_2.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.filters',
              'lab3_2.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.treewalkers',
              'lab3_2.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.treeadapters',
              'lab3_2.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.treebuilders',
              'lab3_2.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.lockfile',
              'lab3_2.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.progress',
              'lab3_2.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.requests',
              'lab3_2.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.packaging',
              'lab3_2.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.cachecontrol',
              'lab3_2.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.cachecontrol.caches',
              'lab3_2.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.webencodings',
              'lab3_2.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.pkg_resources',
              'lab3_2.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal',
              'lab3_2.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.req',
              'lab3_2.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.vcs',
              'lab3_2.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.utils',
              'lab3_2.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.models',
              'lab3_2.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.commands',
              'lab3_2.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.operations',
              'lab3_3.twitter_api.Json_Reader.module'],
    url='',
    license='',
    author='User',
    author_email='',
    description=''
)
